spring:
  application:
    name: parcialFinalNCapas012025

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/supportdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  app:
    jwt-secret: dd1c0c25edf2320965c59832612f58a9ab84f99ce66f8c3ae559fef5bc85fb58
    jwt-expiration-time: 86400000 # 100 days